name: Compile VN's CV

on:
  push:
    branches:
      - vn

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install fonts
      run: |
        apt update
        apt install --yes \
          fonts-roboto \
          fonts-adobe-sourcesans3 \
          ;

    - name: Compile
      run: make

    - name: Mark repo safe for git
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Commit compiled PDF
      uses: EndBug/add-and-commit@v9
      with:
        author_name: github-actions[bot]
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: "chore: Update compiled pdf files"
        add: varun/cv.pdf
        push: true
