name: Compile VN's CV

on:
  push:
    branches:
      - vn

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install fonts
      run: |
        sudo apt update
        sudo apt install --yes \
          fonts-roboto \
          fonts-adobe-sourcesans3 \
          ;

    - name: Build with latex-action
      uses: xu-cheng/latex-action@v2
      with:
        root_file: varun/cv.tex
        work_in_root_file_dir: true
        latexmk_use_xelatex: true
        args: -interaction=nonstopmode -file-line-error -output-directory=varun
        post_compile: "latexmk -c"

    - name: Commit compiled PDF
      uses: EndBug/add-and-commit@v9
      with:
        author_name: github-actions[bot]
        author_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: "ci(vn): Update compiled pdf files"
        add: varun/cv.pdf
        push: true